### PR TITLE
The big merge

### PR DESCRIPTION
**Pull request by farblos**
## The Big Merge

1. Back out the changes since commit 1f77917 to temporarily get rid of all inadvertent whitespace changes.
2. Merge IDCS authentication support.
3. Re-add the changes on master since commit 1f77917 but without the whitespace changes.
4. Merge Eclipse project specific settings.
5. Reformat the source code with Eclipse in a separate commit.
6. Post-process Eclipse's reformatting.
7. Bump the version to 1.1.0.  I think we could be a bit more generous with the versions, at least this PR provides some new features.

## IDCS Authentication Support

Use basic authentication by default, but fall back to other
alternatives if needed.  Implement some other minor fixes.

OraclePatchDownloader.java:

- Factor out authentication to a separate method and use that.
- Use a separate page to trigger authentication, not the initial
  patch search page.
- Add support for IDCS-based authentication.  Suppress JavaScript
  errors caused by that.
- Provide a command line option to control the authentication
  methods being used.

README.md:

- Remove note that getMOSPatch is broken.
- Sync option description from online help.
- Add description of authentication methods.

## Implement Various Changes

- Silence Eclipse's warnings.
- Add more warn methods, defer search errors.
- Fix integer overflow with large patches > 2GB.
- Add more progress methods, show checksums only if needed.
- Add more annotations, format protectors.

## Eclipse Project Specific Settings

.dir-locals.el:

- Add project specific Emacs configuration.

.settings/org.eclipse.core.resources.prefs:

- Configure project encoding as UTF-8.

.settings/org.eclipse.jdt.core.prefs,
.settings/org.eclipse.jdt.ui.prefs:

- Configure project specific Eclipse formatter, cleanup, import
  order, and auto save.

README.md, assets/eclipse-*.png:

- Document editor preferences for Eclipse and Emacs in a new
  section "Contributing".

### CODE REVIEW

**Comment by farblos** [comment]
Hi @ojehle,

this is a huge PR ...

- Please check and test the changes.  To give the new IDCS authentication a try, specify `--authmeth IDCS` on the command line.
- Please also check whether you are comfortable with the project specific Eclipse settings. I hope that now all Eclipse users of this project should automatically use these settings.  You probably should restart Eclipse after pulling the changes to your local repository. I added a new section "Contributing" to the readme that provides documentation and screenshots.
- If everything looks fine, you might as well release a new version. I have prepared the files to use version 1.1.0, since we already have released quite a number of new features.
- Ah, and finally this PR closes also issue #14!

Thanks!

**Comment by ojehle** [comment]
Looks ok for me :-) thanks for the big work....  
i will checkout the git again to my eclipse and will look, if he recognize the project settings.

**Comment by ojehle** [comment]
Test Eclipse settings successfull

Deleted the existing Eclipse project (also files) 
git clone
import in eclipse.
reformat the existing source  ----> Nothing changed -> WORKS !!!


Thanks!

**Comment by farblos** [comment]
Great, thanks for testing!

**Pull request merged**
